### ISSUE TITLE
Exception in v2.4: ClassCastException

### ISSUE THREAD

**Issue by cvdenzen** [mattjlewis/pigpioj#8]
Every now and then (maybe when the pigpiod server is not running?) a call to PigpioSocket.i2cReadI2CBlockData throws an exception:
'''
Caused by: java.lang.ClassCastException: class uk.pigpioj.PigpioSocket$ResponseMessage cannot be cast to class uk.pigpioj.PigpioSocket$ByteArrayResponseMessage (uk.pigpioj.PigpioSocket$ResponseMessage and uk.pigpioj.PigpioSocket$ByteArrayResponseMessage are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @ed3eb6)
        at uk.pigpioj.PigpioSocket.i2cReadI2CBlockData(PigpioSocket.java:738) ~[!/:2.4]
        at nl.vandenzen.iot.beans.BME280Driver.read(BME280Driver.java:268) ~[!/:?]
        at nl.vandenzen.iot.beans.BME280Driver.getSensorValues(BME280Driver.java:386) ~[!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.camel.support.ObjectHelper.invokeMethodSafe(ObjectHelper.java:352) ~[!/:3.6.0]
        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:474) ~[!/:3.6.0]
        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:296) ~[!/:3.6.0]
        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:266) ~[!/:3.6.0]
        at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:145) ~[!/:3.6.0]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:54) ~[!/:3.6.0]
        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:404) ~[!/:3.6.0]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) ~[!/:3.6.0]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) ~[!/:3.6.0]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) ~[!/:3.6.0]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:288) ~[!/:3.6.0]
        at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83) ~[!/:3.6.0]
        at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:41) ~[!/:3.6.0]
        at org.apache.camel.component.quartz.CamelJob.execute(CamelJob.java:62) ~[!/:3.6.0]
        ... 2 more
'''

**Comment by mattlewismule** [comment]
Interesting. From the stack trace I can see you are interfacing with a BME280. I have one of those connected right now so can try reproduce. Is there any possibility that you have other pigpio commands happening in separate threads at the same time?

**Comment by cvdenzen** [comment]
Hello,

It is very likely that other commands happen in other threads. I also have a brightness bh1750 sensor and a 16x2 display running in the same Apache Camel instance. Thank you for this suggestion  So maybe I have to synchronize it in some way..
Source is in directory pilightmqttosgi on https://github.com/cvdenzen/mijnsensors.

Greetings,
Carl van Denzen

**Comment by mattjlewis** [comment]
Out of curiosity are there any other messages printed out to standard error? Looking at that stack trace it looks like a wrong response type has got through somehow. This code checks the type of the response message which is meant to prevent that:
```
				if (rm.cmd != message.cmd) {
					System.err.println("Unexpected response: " + rm + ". Was expecting " + message.cmd);
				}

```
I've just pushed 2.5.1 that has some additional error handling around uk.pigpioj.PigpioSocket.i2cReadI2CBlockData - would you mind testing that and letting me know of any output to standard error and stack trace.

**Comment by mattjlewis** [comment]
I can't seem to recreate this issue using the pigpioj provider in diozero (www.diozero.com). I've created this test class that does a lot of concurrent I2C calls: https://github.com/mattjlewis/diozero/blob/master/diozero-sampleapps/src/main/java/com/diozero/sampleapps/I2CPerfTest.java.
I've run this on my local laptop using this command:
java -DPIGPIOD_HOST=pi4.local -cp diozero-sampleapps-1.0.0-SNAPSHOT.jar:diozero-provider-pigpio-1.0.0-SNAPSHOT.jar:pigpioj-java-2.5.jar com.diozero.sampleapps.I2CPerfTest
I can try recreate using just pigpioj - is there a reason that you are using pigpioj rather than diozero?

**Comment by cvdenzen** [comment]
Let’s wait what happens with 2.5.1. The reason I don’t use diozero is, that I can get bugs fom both diozero and from pigpio. And the development chain is longer, new versions of pipioj would take longer to get into diozero and my raspberry. I like to have the newest bugs:-)
I am curious what causes this error and hope it has not vanished.
Maybe diozero synchronizes some methods? Hope we will find out.

**Comment by mattjlewis** [comment]
I’m the maintainer for both libraries and can categorically state that pigpioj works perfectly with diozero - that is what I have developed it for in the first place. Plus I have implemented support for BME280 already - see my I2C stress test code.
I’ve not looked at your code too much but my guess is that you are missing some synchronisation. I can maybe try create a simple test case.
